# Generated by Django 3.2.8 on 2021-10-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='email',
            field=models.EmailField(default='samy.sellami@hotmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
