# Generated by Django 3.2.8 on 2021-10-22 10:04

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchapp', '0003_alter_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
