# Generated by Django 3.2.8 on 2021-10-22 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchapp', '0007_alter_notification_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='invalid email, plase the format xxx@xxx.xx')]),
        ),
        migrations.AlterField(
            model_name='notification',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='invalid phone number, please use the format +7xxxxxxxxxx', regex='^\\+?7?\\d{8,15}$')]),
        ),
    ]
