# Generated by Django 3.2.8 on 2021-10-22 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchapp', '0008_auto_20211022_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='invalid email, please use the format xxx@xxx.xx')]),
        ),
    ]
