# Generated by Django 3.2.8 on 2021-10-24 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchapp', '0012_auto_20211023_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='invalid phone number, please use the format +7xxxxxxxxxx', regex='^\\+?7?\\d{9,15}$')]),
        ),
    ]
